# Generated by Django 5.1.1 on 2024-09-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_news_created_time_alter_news_published_time_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
