# Generated by Django 5.1.1 on 2024-09-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_alter_comment_news_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='active',
        ),
    ]
