# Generated by Django 5.1.1 on 2024-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_photo_profile_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
